name: Create Release from Changelog

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Extract changelog
        run: |
          VERSION=${{ steps.version.outputs.version }}

          sed 's/\r$//' CHANGELOG.md > clean.md

          echo "## Unreleased" > notes.md
          sed -n '/^## \[Unreleased\]/,/^## \[/p' clean.md | tail -n +2 >> notes.md

          echo "" >> notes.md

          sed -n "/^## \[$VERSION\]/,/^## \[/p" clean.md | tail -n +2 >> notes.md

      # Install tools
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      # Build with CMake
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      # Debug (usefull first time)
      - name: Debug build output
        run: |
          echo "===== BUILD CONTENT ====="
          ls -R build

      # Find and zip the .exe
      - name: Create zip
        run: |
          mkdir -p dist

          FILE=$(find build -type f -executable -name "FrostformEngine*" | head -n 1)

          if [ -z "$FILE" ]; then
            echo "ERROR: executable not found"
            exit 1
          fi

          echo "Found executable: $FILE"

          zip -j dist/FrostformEngine-${{ github.ref_name }}.zip "$FILE"

          ls -l dist

      # Release GitHub
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: notes.md
          files: |
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}